version: '3.8'

services:
  # =============================================================================
  # DOCUMENT PROCESSING - Unstructured.io Worker (Supabase Integration)
  # =============================================================================
  unstructured-worker:
    build:
      context: .
      dockerfile: Dockerfile.unstructured
    container_name: athenai-unstructured
    restart: unless-stopped
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      UNSTRUCTURED_API_KEY: ${UNSTRUCTURED_API_KEY}
      UNSTRUCTURED_API_URL: ${UNSTRUCTURED_API_URL:-https://api.unstructured.io}
      EMBEDDING_MODEL: ${EMBEDDING_MODEL:-text-embedding-3-small}
      WORKER_CONCURRENCY: ${WORKER_CONCURRENCY:-2}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    volumes:
      - ./data/unstructured/input:/app/input
      - ./data/unstructured/output:/app/output
      - unstructured_logs:/app/logs
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - athenai-network

  # =============================================================================
  # MAIN APPLICATION - AthenAI with Document Agent (Supabase Integration)
  # =============================================================================
  athenai:
    build: .
    container_name: athenai-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./data/unstructured/input:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - athenai-network

# =============================================================================
# PERSISTENT VOLUMES
# =============================================================================
volumes:
  unstructured_logs:

# =============================================================================
# NETWORKS
# =============================================================================
networks:
  athenai-network:
    driver: bridge
