global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'neov3-local'
    environment: 'development'

rule_files:
  - "/etc/prometheus/rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 5s

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 10s

  - job_name: 'neo4j'
    static_configs:
      - targets: ['neo4j:2004']
    scrape_interval: 10s

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    scrape_interval: 10s

  - job_name: 'api-service'
    static_configs:
      - targets: ['api-service:5000']
    scrape_interval: 5s
    metrics_path: '/metrics'

  - job_name: 'n8n'
    static_configs:
      - targets: ['n8n:5678']
    scrape_interval: 10s
    metrics_path: '/metrics'


  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 30s
    metrics_path: '/metrics'

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
    scrape_interval: 15s
    metrics_path: '/metrics'

  - job_name: 'cadvisor'
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/cadvisor.yml
    scrape_interval: 10s

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
    scrape_interval: 30s
    metrics_path: '/metrics'

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://api-service:5000/system/health
          - http://n8n:5678/healthz
          - http://grafana:3000/api/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'agent-lifecycle-manager'
    static_configs:
      - targets: ['agent-lifecycle-manager:8001']
    scrape_interval: 15s

  - job_name: 'knowledge-drift-detector'
    static_configs:
      - targets: ['knowledge-drift-detector:8002']
    scrape_interval: 30s

  - job_name: 'self-healing-monitor'
    static_configs:
      - targets: ['self-healing-monitor:8003']
    scrape_interval: 15s

  # LangSmith metrics via OpenTelemetry collector
  - job_name: 'langsmith-otel'
    static_configs:
      - targets: ['otel-collector:8889']
    scrape_interval: 30s
    metrics_path: '/metrics'
