apiVersion: v1
kind: Service
metadata:
  name: agent-lifecycle-manager
  namespace: neov3
  labels:
    app: agent-lifecycle-manager
spec:
  selector:
    app: agent-lifecycle-manager
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  type: ClusterIP
