apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-lifecycle-manager
  namespace: neov3
  labels:
    app: agent-lifecycle-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-lifecycle-manager
  template:
    metadata:
      labels:
        app: agent-lifecycle-manager
    spec:
      containers:
        - name: agent-lifecycle-manager
          image: neov3/agent-lifecycle-manager:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8081
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          envFrom:
            - configMapRef:
                name: neov3-config
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
