groups:
  - name: db-observability
    interval: 1m
    rules:
      # Postgres error rate > 2% over 10m
      - alert: PostgresHighErrorRate
        expr: |
          (sum(rate(database_operations_total{database_type="postgres",status="error"}[10m])) by ()
          /
          sum(rate(database_operations_total{database_type="postgres"}[10m])) by ()) > 0.02
        for: 10m
        labels:
          severity: warning
          service: api
          component: postgres
        annotations:
          summary: "Postgres error rate high (>2% for 10m)"
          description: "Investigate failing queries and DB health."

      # Postgres p95 latency > 500ms over 10m
      - alert: PostgresHighLatencyP95
        expr: |
          histogram_quantile(0.95,
            sum by (le)(rate(database_query_duration_seconds_bucket{database_type="postgres"}[10m]))) > 0.5
        for: 10m
        labels:
          severity: warning
          service: api
          component: postgres
        annotations:
          summary: "Postgres p95 latency > 500ms (10m)"
          description: "Queries are slower than expected. Check load, locks, and indexes."

      # Neo4j error rate > 2% over 10m
      - alert: Neo4jHighErrorRate
        expr: |
          (sum(rate(database_operations_total{database_type="neo4j",status="error"}[10m])) by ()
          /
          sum(rate(database_operations_total{database_type="neo4j"}[10m])) by ()) > 0.02
        for: 10m
        labels:
          severity: warning
          service: api
          component: neo4j
        annotations:
          summary: "Neo4j error rate high (>2% for 10m)"
          description: "Investigate failing Cypher queries and driver connectivity."

      # Neo4j p95 latency > 750ms over 10m
      - alert: Neo4jHighLatencyP95
        expr: |
          histogram_quantile(0.95,
            sum by (le)(rate(database_query_duration_seconds_bucket{database_type="neo4j"}[10m]))) > 0.75
        for: 10m
        labels:
          severity: warning
          service: api
          component: neo4j
        annotations:
          summary: "Neo4j p95 latency > 750ms (10m)"
          description: "Cypher queries are slower than expected. Check Neo4j CPU/IO and query plans."

      # No DB activity (possible ingestion outage)
      - alert: DatabaseNoActivity
        expr: |
          (absent(sum(rate(database_operations_total[5m])) by ()))
        for: 10m
        labels:
          severity: critical
          service: api
          component: database
        annotations:
          summary: "No database activity detected for 10m"
          description: "API may be down or not issuing DB queries. Check API /metrics and service health."
