apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: neov3
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: api-service
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3
images:
  - name: neov3/api
    newTag: stable
